#!/bin/sh

ADDONNAME=homekit-ccu
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
HAPDIR=${ADDON_DIR}/node_modules/homekit-ccu
ADDONWWW_DIR=/usr/local/etc/config/addons/www
ADDONCFG_DIR=${CONFIG_DIR}/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d

# make sure this addon is only executed on
# supported platforms

if [ "$1" == "HM-RASPBERRYMATIC" ]  || [ "$1" == "CCU3" ] ; then

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# ensure a compatible Node.js version is available
cp -af hap/etc/preinstall.sh /tmp/preinstall.sh
chmod +x /tmp/preinstall.sh
/tmp/preinstall.sh
rm -f /tmp/preinstall.sh

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# copy addon
mkdir -p ${ADDONCFG_DIR}/etc
mkdir -p ${CONFIG_DIR}/${ADDONNAME}

#create the www stuff - install static files available before node_modules
mkdir -p ${ADDONWWW_DIR}/${ADDONNAME}
cp -af hap/etc/www/update-check.cgi ${ADDONWWW_DIR}/${ADDONNAME}
cp -af hap/etc/www/homekit-ccu-logo.png ${ADDONWWW_DIR}/${ADDONNAME}

# open proxy ports in firewall via TCL library (persists through WebUI saves)
if [ -f /lib/libfirewall.tcl ]; then
  tclsh - <<'FWEOF'
source /lib/libfirewall.tcl
Firewall_loadConfiguration
global Firewall_USER_PORTS
foreach port {9874 49874} {
  if {[lsearch $Firewall_USER_PORTS $port] == -1} {
    lappend Firewall_USER_PORTS $port
  }
}
Firewall_saveConfiguration
Firewall_configureFirewall
FWEOF
fi

# copy startup script
cp -af rc.d/* ${RCD_DIR}
# copy installer
cp -af hap/etc/preinstall.sh ${ADDONCFG_DIR}/etc
chmod +x ${ADDONCFG_DIR}/etc/preinstall.sh
cp -af hap/etc/start.sh ${ADDONCFG_DIR}/etc
chmod +x ${ADDONCFG_DIR}/etc/start.sh
cp -af hap/etc/postinstall.sh ${ADDONCFG_DIR}/etc
chmod +x ${ADDONCFG_DIR}/etc/postinstall.sh
# copy the npm package so postinstall.sh can install from it after reboot
cp -af hap/etc/homekit-ccu.tgz ${ADDONCFG_DIR}/etc/homekit-ccu.tgz

#build system launcher
chmod +x ${RCD_DIR}/${ADDONNAME}
chmod +x ${ADDONWWW_DIR}/${ADDONNAME}/update-check.cgi

sync

#check if the plugin is allready installd
if [ ! -f ${ADDON_DIR}/node_modules/homekit-ccu/index.js ]; then
# new installation so reboot and the launcher will install the rest of the system
  exit 10
else
#so we have an update here and there is no need to reboot the Rasberrymatic will exit without an reboot
  exit 0
fi

fi
